web/map_quest/urls.py
from django.urls import path

from map_quest.views import index
from map_quest.views import dataset_detail
from map_quest.views import dataset_create
from map_quest.views import dataset_delete
from map_quest.views import dataset_update
from map_quest.views import subset_list

app_name = 'map_quest'

urlpatterns = [
    # Si besoin d'urls supplémentaires
    path('accueil/', index, name='index'),
    path('dataset/<int:dataset_id>/', dataset_detail, name='dataset_detail'),
    path('dataset/<int:dataset_id>/delete/', dataset_delete, name='dataset_delete'),
    path('dataset/<int:dataset_id>/update/', dataset_update, name='dataset_update'),
    path('dataset/<int:dataset_id>/subset/', subset_list, name='subset_list'),
    path('dataset/', dataset_create, name='dataset_create'),

]

web/map_quest/models.py
from django.contrib.gis.db import models


class Dataset(models.Model):

    def logo_dir(instance, filename):
        return "dataset_{0}/logo/{1}".format(instance.pk, filename)

    label = models.CharField('Label', max_length=2048)

    description = models.TextField('Description')

    logo = models.ImageField('Logo', upload_to=logo_dir, blank=True, null=True)

    created_on = models.DateTimeField('Crée le', auto_now_add=True)

    @property
    def nb_subsets(self):
        return self.subsets.count()

    @property
    def attachments(self):
        return [subset.attachement for subset in self.subsets.all()]


class ContextualGeom(models.Model):

    label = models.CharField('Label', max_length=2048)

    color = models.CharField(
        verbose_name='Couleur', max_length=7, blank=True, null=True
    )

    is_active = models.BooleanField('Est valide', default=True)

    class Meta:
        abstract = True


class Node(ContextualGeom):

    geom = models.PointField('POI', srid=4326)


class Edge(ContextualGeom):

    geom = models.MultiLineStringField('Ligne', srid=4326)


class Polygon(ContextualGeom):

    geom = models.MultiPolygonField('Zones', srid=4326)


class Subset(models.Model):

    def attachement_dir(instance, filename):
        return "dataset_{0}/subseet_{1}/attachement/{2}".format(instance.dataset.pk, instance.pk, filename)

    dataset = models.ForeignKey('map_quest.Dataset', on_delete=models.CASCADE, related_name='subsets')

    nodes = models.ManyToManyField('map_quest.Node')

    edges = models.ManyToManyField('map_quest.Edge')

    polygones = models.ManyToManyField('map_quest.Polygon')

    color = models.CharField(
        verbose_name='Couleur par défaut', max_length=7, blank=True, null=True
    )

    context = models.TextField('Contexte')

    attachement = models.FileField(
        'Fichier joint', upload_to=attachement_dir, blank=True, null=True
    )

web/map_quest/forms.py
from django import forms

from map_quest.models import Dataset


class DatasetForm(forms.ModelForm):

    class Meta:
        model = Dataset
        fields = '__all__'

web/map_quest/views.py
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.shortcuts import redirect

from map_quest.forms import DatasetForm
from map_quest.models import Dataset
from map_quest.models import Subset


def index(request):
    datasets = Dataset.objects.all()
    return render(request, 'map_quest/index.html', {'datasets': datasets})


def dataset_detail(request, dataset_id):
    dataset = get_object_or_404(Dataset, pk=dataset_id)
    return render(request, 'map_quest/dataset_detail.html', {'dataset': dataset})


def dataset_create(request):
    if request.method != 'POST':
        form = DatasetForm()
        return render(request, 'map_quest/dataset_create.html', {'form': form})


def dataset_delete(request, dataset_id):
    dataset = get_object_or_404(Dataset, pk=dataset_id)
    dataset.delete()
    return redirect('map_quest:index')


def dataset_update(request, dataset_id):
    dataset = get_object_or_404(Dataset, pk=dataset_id)
    if request.method != 'POST':
        form = DatasetForm(instance=dataset)
    else:
        form = DatasetForm(request.POST, instance=dataset)
        if form.is_valid():
            form.save()
    return render(request, 'map_quest/dataset_edit.html', {'form': form})


def subset_list(request, dataset_id):
    dataset = get_object_or_404(Dataset, pk=dataset_id)
    subsets = Subset.objects.filter(dataset=dataset)
    return render(request, 'map_quest/subset_list.html', {'dataset': dataset, 'subsets': subsets})

web/map_quest/templates/map_quest/alert_messages.html
{% if messages %}
<div class="ui stackable grid">
  <div class="row">
    <div class="eight wide column">
      {% for message in messages %}
        {% if message.tags == 'success' %}
        <div class="ui success message">
          <div class="header">
            <i class="success thumbs up outline icon"></i> {{ message }}
          </div>
        </div>
        {% elif message.tags == 'info' %}
        <div class="ui info message">
          <div class="header">
            <i class="info circle icon"></i> {{ message }}
          </div>
        </div>
        {% elif message.tags == 'error' %}
        <div class="ui error message">
          <div class="header">
            <i class="error circle icon"></i> {{ message }}
          </div>
        </div>
        {% endif %}
      {% endfor %}
    </div>
  </div>
</div>
<br />
{% endif %}

web/map_quest/templates/map_quest/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <title>{% block title %}{% endblock %}</title>
  <link rel="shortcut icon" type="image/png" href="{% static 'map_quest/img/favicon.ico' %}"/>

  <!-- jQuery Core 3.3.1 -->
  <script src="{% static 'map_quest/resources/jquery-3.4.1/jquery-3.4.1.min.js'%}"></script>
  <!-- Semantic UI -->
  <link rel="stylesheet" href="{% static 'map_quest/resources/semantic-ui-2.4.2/semantic.min.css' %}" />
  <script src="{% static 'map_quest/resources/semantic-ui-2.4.2/semantic.min.js' %}"></script>

  <!-- Leaflet -->
  <link rel="stylesheet" href="{% static 'map_quest/resources/leaflet-1.5.1/leaflet.css' %}" />
  <script src="{% static 'map_quest/resources/leaflet-1.5.1/leaflet.js' %}"></script>
  <!-- Leaflet Draw -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.4/leaflet.draw.css" integrity="sha256-XzD3RpaHPv7lzX9qt+2n1j5cWj48O24KsgaGYpKN8x8=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.4/leaflet.draw.js" integrity="sha256-siofc4Uwjlra3YWkwthOn8Uj69cNN4aMug/iOHNiRgs=" crossorigin="anonymous"></script>

  <!-- WellKnown JS -->
  <script src="https://cdn.rawgit.com/mapbox/wellknown/master/wellknown.js"></script>
  <!-- Turf.js -->
  <script src="https://cdn.jsdelivr.net/npm/@turf/turf@5/turf.min.js"></script>

  <!-- Custom -->
  <link rel="stylesheet" href="{% static 'map_quest/css/base.css' %}"/>
  <script src="{% static 'map_quest/js/base.js' %}"></script>
  {% block custom_resources %}
  {% endblock %}

</head>

<body>
  <header>
    <div class="ui container">
      <div class="ui inverted icon menu">
        <a href="{% url 'map_quest:index' %}" class="header item">
          <img class="ui mini right spaced image" src="{% static 'map_quest/img/logo.png' %}">
          {{ APPLICATION_NAME }}
        </a>
      </div>
    </div>
  </header>
  <main>
      {% include "map_quest/alert_messages.html" %}

      {% block content %}
      {% endblock %}
    </div>
  </main>

  <footer>
    <div class="ui compact text menu">
      <a class="item" href="{% url 'map_quest:index' %}">Aide</a>
    </div>
  </footer>

</body>
</html>

web/map_quest/templates/map_quest/dataset_detail.html
{% extends "map_quest/base.html" %}

{% load static %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<div class="row">
  <div class="fourteen wide column">
    <h1 class="ui header">
      <div class="content">
        {{ dataset.label }}

          <div class="ui icon right floated compact buttons">
            <a href="{% url 'map_box:dataset_update' dataset_id=dataset.pk %}" class="ui button button-hover-orange">
              <i class="inverted grey pencil alternate icon"></i>
            </a>
            <a id="dataset-delete" class="ui button button-hover-red">
              <i class="inverted grey trash alternate icon"></i>
            </a>
          </div>

        <div class="ui hidden divider"></div>
        <div class="sub header">
          {{ dataset.description|linebreaks }}
        </div>
      </div>
    </h1>
  </div>
</div>

<div class="row">
  <div class="seven wide column">
    <table class="ui very basic table">
      <tbody>
        <tr>
          <td>Label</td>
          <td>{{ dataset.label }}</td>
        </tr>
        <tr>
          <td>Description</td>
          <td>{{ dataset.description|linebreaks }}</td>
        </tr>
        <tr>
          <td>Date de création</td>
          <td>{{ dataset.created_on }}</td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="seven wide column">
    <a id="feature-list-link" href="{% url 'map_quest:subset_list' dataset_id=dataset.id %}">
      <div id="map"></div>
    </a>
  </div>
</div>

<div class="row">
  <div class="seven wide column">
    <h2 class="ui header">Pièces jointes</h2>

    <div class="ui divided items">
      {% for pj in dataset.attachments %}
        <div class="item">
          <a class="ui tiny image" target="_blank" href="{{ pj.url }}">
            {% if pj.extension == '.pdf' %}
              <img src="{% static 'map_quest/img/pdf.png' %}">
            {% else %}
              <img src="{{ pj.url }}">
            {% endif %}
          </a>
          <div class="middle aligned content">
            <a class="header" target="_blank" href="{{ pj.url }}">{{ pj.filename }}</a>
            <div class="description">
              {{ pj.content_type }}
            </div>
          </div>
        </div>
        {% empty %}
        <i>Aucune pièce jointe associée au {{ DATASETS_VERBOSE_NAME }}.</i>
        {% endfor %}

    </div>
  </div>

  <div class="seven wide column">
    <h2 class="ui header">Activité et commentaires</h2>
    <p>TODO</p>
  </div>
</div>

<div class="ui mini modal subscription">
  <i class="close icon"></i>
  <div class="ui icon header">
    <i class="trash alternate icon"></i>
    Supprimer le {{ DATASETS_VERBOSE_NAME }}
  </div>
  <div class="actions">
    <form action="{% url 'map_box:dataset_delete' dataset=dataset_id %}" method="POST">
      {% csrf_token %}
      <input type="hidden" name="_method" value="delete">
      <button type="submit" class="ui red compact fluid button">
        Confirmer la suppression
      </button>
    </form>
  </div>
</div>

{% endblock %}

{% block custom_resources %}
<style>
  #map {
    width: 100%;
    height: 100%;
    min-height: 250px;
  }
  #feed-event .event {
    margin-bottom: 1em;
  }
  #feed-event .event .date {
    margin-right: 1em !important;
  }
  #feed-event .event .extra.text {
    margin-left: 107px;
    margin-top: 0;
  }
</style>

<script type="text/javascript">
  function truncate(n, len) {
    var ext = n.substring(n.lastIndexOf(".") + 1, n.length).toLowerCase()
    var filename = n.replace('.' + ext, '')
    if (filename.length <= len) {
      return n
    }
    filename = filename.substr(0, len) + (n.length > len ? '[...]' : '')
    return filename + '.' + ext
  }

  $(document).on('change', '#form-comment #attachment_file', function () {
    var logoFile = $(this).prop('files')[0]
    $(this).parent().children('label').children('.label').html(truncate(logoFile.name, 10))
    $('#{{ comment_form.title.id_for_label }}').val(truncate(logoFile.name, 10))
  })

  $(document).ready(function() {

    $('#dataset-delete').click(function() {
      $('.mini.modal').modal('show')
    })

    var map = L.map('map', {zoomControl: false}).setView({{ DEFAULT_MAP_VIEW.center }}, {{ DEFAULT_MAP_VIEW.zoom }})

    map.on("moveend", function() {
      // update link to feature list with map zoom and center
      var $featureListLink = $("#feature-list-link")
      var baseUrl = $featureListLink.attr("href").split("?")[0]
      var queryString = $.param([
        {name: "zoom", value: map.getZoom()},
        {name: "lat", value: map.getCenter().lat},
        {name: "lng", value: map.getCenter().lng},
      ])
      $featureListLink.attr("href", baseUrl + "?" + queryString)
    });

    {% if layers %}
      {% for layer in layers %}
        var options = {{ layer.options|safe }}
        {% if layer.schema_type == "wms" %}
          L.tileLayer.wms('{{ layer.service }}', options).addTo(map)
        {% elif layer.schema_type == "tms" %}
          L.tileLayer('{{ layer.service }}', options).addTo(map)
        {% endif %}
      {% endfor %}
    {% else %}
      L.tileLayer('{{ SERVICE }}', JSON.parse('{{ OPTIONS | escapejs }}')).addTo(map)
    {% endif %}

    map.dragging.disable()
    map.doubleClickZoom.disable()
    map.scrollWheelZoom.disable()

    var featureGroup = new L.FeatureGroup()
    var geomFeatureJSON = wellknown.parse("{{ feature.geom.wkt }}")
    var geomJSON = turf.flip(geomFeatureJSON)

    if (geomJSON.type === 'Point') {
      L.circleMarker(geomJSON.coordinates, {
        color: '{{ feature.feature_type.color }}',
        radius: 4,
        fillOpacity: 0.3,
        weight: 1
      }).addTo(featureGroup)
    } else if (geomJSON.type === 'LineString') {
      L.polyline(geomJSON.coordinates, {
        color: '{{ feature.feature_type.color }}',
        weight: 1.5
      }).addTo(featureGroup)
    } else if (geomJSON.type === 'Polygon') {
      L.polygon(geomJSON.coordinates, {
        color: '{{ feature.feature_type.color }}',
        weight: 1.5,
        fillOpacity: 0.3
      }).addTo(featureGroup)
    }
    map.addLayer(featureGroup);
    map.fitBounds(featureGroup.getBounds())
  })
</script>
{% endblock %}

web/map_quest/templates/map_quest/index.html
{% extends "map_quest/base.html" %}

{% load static %}

{% block title %}{{ title }}{% endblock %}

{% block content %}

<div class="fourteen wide column">
  <img class="ui centered small image" src="{% static 'map_quest/img/logo-large.png' %}">
  <h2 class="ui center aligned icon header">
    <div class="content">
      {{ APPLICATION_NAME }}
      <div class="sub header">{{ APPLICATION_ABSTRACT }}</div>
    </div>
  </h2>

  <h4 id="les_projets" class="ui horizontal divider header">{{ DATASETS_VERBOSE_NAME_PLURAL }}</h4>
  <div class="ui divided items">
    {% for dataset in datasets %}
    <div class="item">
      <div class="ui tiny image">
        <img src="{{ dataset.logo }}">
      </div>
      <div class="middle aligned content">
        <a class="header" href="{% url 'map_quest:dataset_detail' dataset_id=dataset.pk %}">{{ dataset.label }}</a>
        <div class="description">
          <p>{{ dataset.description }}</p>
        </div>

        <div class="meta">
          <span class="right floated">
            <i class="calendar icon"></i>&nbsp; {{ dataset.created_on }}
          </span>
          <span data-tooltip="Nombre d'elements">
            {{ project.nb_subsets }}&nbsp;<i class="user icon"></i>
          </span>
        </div>
      </div>
    </div>
    {% empty %}
    <span>Aucun {{ DATASETS_VERBOSE_NAME }} n'est disponible.</span>
    {% endfor %}
    <div class="item">
    </div>
  </div>

  <a class="ui green basic button" href="{% url 'map_quest:dataset_create' %}">
    <i class="plus icon"></i> Créer un nouveau {{ DATASETS_VERBOSE_NAME }}
  </a>

</div>
{% endblock content %}